# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.6
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_kovan', [dirname(__file__)])
        except ImportError:
            import _kovan
            return _kovan
        if fp is not None:
            try:
                _mod = imp.load_module('_kovan', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _kovan = swig_import_helper()
    del swig_import_helper
else:
    import _kovan
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def power_level():
  return _kovan.power_level()
power_level = _kovan.power_level

def a_button_set_text(*args):
  return _kovan.a_button_set_text(*args)
a_button_set_text = _kovan.a_button_set_text

def b_button_set_text(*args):
  return _kovan.b_button_set_text(*args)
b_button_set_text = _kovan.b_button_set_text

def z_button_set_text(*args):
  return _kovan.z_button_set_text(*args)
z_button_set_text = _kovan.z_button_set_text

def a_button():
  return _kovan.a_button()
a_button = _kovan.a_button

def b_button():
  return _kovan.b_button()
b_button = _kovan.b_button

def z_button():
  return _kovan.z_button()
z_button = _kovan.z_button

def get_servo_position():
  return _kovan.get_servo_position()
get_servo_position = _kovan.get_servo_position

def set_servo_position(*args):
  return _kovan.set_servo_position(*args)
set_servo_position = _kovan.set_servo_position
# This file is compatible with both classic and new-style classes.


