/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class AbstractButton {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AbstractButton(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AbstractButton obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        kovanJNI.delete_AbstractButton(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setText(String text) {
    kovanJNI.AbstractButton_setText(swigCPtr, this, text);
  }

  public String text() {
    return kovanJNI.AbstractButton_text(swigCPtr, this);
  }

  public boolean isTextDirty() {
    return kovanJNI.AbstractButton_isTextDirty(swigCPtr, this);
  }

  public void setPressed(boolean pressed) {
    kovanJNI.AbstractButton_setPressed(swigCPtr, this, pressed);
  }

  public boolean isPressed() {
    return kovanJNI.AbstractButton_isPressed(swigCPtr, this);
  }

  public boolean isNotPressed() {
    return kovanJNI.AbstractButton_isNotPressed(swigCPtr, this);
  }

}
