/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Battery {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Battery(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Battery obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        kovanJNI.delete_Battery(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static float powerLevel() {
    return kovanJNI.Battery_powerLevel();
  }

  public Battery() {
    this(kovanJNI.new_Battery(), true);
  }

}
