/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


	#include "battery.hpp"
	#include "button.hpp"
	#include "servo.hpp"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jfloat JNICALL Java_kovanJNI_Battery_1powerLevel(JNIEnv *jenv, jclass jcls) {
  jfloat jresult = 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  result = (float)Battery::powerLevel();
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_kovanJNI_new_1Battery(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Battery *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Battery *)new Battery();
  *(Battery **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_kovanJNI_delete_1Battery(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Battery *arg1 = (Battery *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Battery **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_kovanJNI_delete_1AbstractButton(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  AbstractButton *arg1 = (AbstractButton *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(AbstractButton **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_kovanJNI_AbstractButton_1setText(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  AbstractButton *arg1 = (AbstractButton *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AbstractButton **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return ;
  }
  (arg1)->setText((char const *)arg2);
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_kovanJNI_AbstractButton_1text(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  AbstractButton *arg1 = (AbstractButton *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AbstractButton **)&jarg1; 
  result = (char *)((AbstractButton const *)arg1)->text();
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_kovanJNI_AbstractButton_1isTextDirty(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  AbstractButton *arg1 = (AbstractButton *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AbstractButton **)&jarg1; 
  result = (bool)((AbstractButton const *)arg1)->isTextDirty();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_kovanJNI_AbstractButton_1setPressed(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  AbstractButton *arg1 = (AbstractButton *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AbstractButton **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  (arg1)->setPressed(arg2);
}


SWIGEXPORT jboolean JNICALL Java_kovanJNI_AbstractButton_1isPressed(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  AbstractButton *arg1 = (AbstractButton *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AbstractButton **)&jarg1; 
  result = (bool)((AbstractButton const *)arg1)->isPressed();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_kovanJNI_AbstractButton_1isNotPressed(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  AbstractButton *arg1 = (AbstractButton *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AbstractButton **)&jarg1; 
  result = (bool)((AbstractButton const *)arg1)->isNotPressed();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_kovanJNI_AButton_1setText(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  AButton *arg1 = (AButton *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AButton **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return ;
  }
  (arg1)->setText((char const *)arg2);
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_kovanJNI_AButton_1text(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  AButton *arg1 = (AButton *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AButton **)&jarg1; 
  result = (char *)((AButton const *)arg1)->text();
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_kovanJNI_AButton_1isTextDirty(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  AButton *arg1 = (AButton *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AButton **)&jarg1; 
  result = (bool)((AButton const *)arg1)->isTextDirty();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_kovanJNI_AButton_1setPressed(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  AButton *arg1 = (AButton *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AButton **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  (arg1)->setPressed(arg2);
}


SWIGEXPORT jboolean JNICALL Java_kovanJNI_AButton_1isPressed(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  AButton *arg1 = (AButton *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(AButton **)&jarg1; 
  result = (bool)((AButton const *)arg1)->isPressed();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_kovanJNI_new_1AButton(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  AButton *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (AButton *)new AButton();
  *(AButton **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_kovanJNI_delete_1AButton(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  AButton *arg1 = (AButton *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(AButton **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_kovanJNI_BButton_1setText(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  BButton *arg1 = (BButton *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(BButton **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return ;
  }
  (arg1)->setText((char const *)arg2);
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_kovanJNI_BButton_1text(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  BButton *arg1 = (BButton *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(BButton **)&jarg1; 
  result = (char *)((BButton const *)arg1)->text();
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_kovanJNI_BButton_1isTextDirty(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  BButton *arg1 = (BButton *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(BButton **)&jarg1; 
  result = (bool)((BButton const *)arg1)->isTextDirty();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_kovanJNI_BButton_1setPressed(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  BButton *arg1 = (BButton *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(BButton **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  (arg1)->setPressed(arg2);
}


SWIGEXPORT jboolean JNICALL Java_kovanJNI_BButton_1isPressed(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  BButton *arg1 = (BButton *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(BButton **)&jarg1; 
  result = (bool)((BButton const *)arg1)->isPressed();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_kovanJNI_new_1BButton(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  BButton *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (BButton *)new BButton();
  *(BButton **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_kovanJNI_delete_1BButton(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  BButton *arg1 = (BButton *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(BButton **)&jarg1; 
  delete arg1;
}


SWIGEXPORT void JNICALL Java_kovanJNI_ZButton_1setText(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  ZButton *arg1 = (ZButton *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ZButton **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)jenv->GetStringUTFChars(jarg2, 0);
    if (!arg2) return ;
  }
  (arg1)->setText((char const *)arg2);
  if (arg2) jenv->ReleaseStringUTFChars(jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_kovanJNI_ZButton_1text(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  ZButton *arg1 = (ZButton *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ZButton **)&jarg1; 
  result = (char *)((ZButton const *)arg1)->text();
  if (result) jresult = jenv->NewStringUTF((const char *)result);
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_kovanJNI_ZButton_1isTextDirty(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  ZButton *arg1 = (ZButton *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ZButton **)&jarg1; 
  result = (bool)((ZButton const *)arg1)->isTextDirty();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_kovanJNI_ZButton_1setPressed(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  ZButton *arg1 = (ZButton *) 0 ;
  bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ZButton **)&jarg1; 
  arg2 = jarg2 ? true : false; 
  (arg1)->setPressed(arg2);
}


SWIGEXPORT jboolean JNICALL Java_kovanJNI_ZButton_1isPressed(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jboolean jresult = 0 ;
  ZButton *arg1 = (ZButton *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ZButton **)&jarg1; 
  result = (bool)((ZButton const *)arg1)->isPressed();
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_kovanJNI_new_1ZButton(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  ZButton *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (ZButton *)new ZButton();
  *(ZButton **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_kovanJNI_delete_1ZButton(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  ZButton *arg1 = (ZButton *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(ZButton **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_kovanJNI_new_1Servo(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  port_t arg1 ;
  port_t *argp1 ;
  Servo *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(port_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null port_t");
    return 0;
  }
  arg1 = *argp1; 
  result = (Servo *)new Servo(arg1);
  *(Servo **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_kovanJNI_Servo_1setPosition(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  Servo *arg1 = (Servo *) 0 ;
  Servo::ticks_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Servo **)&jarg1; 
  arg2 = (Servo::ticks_t)jarg2; 
  (arg1)->setPosition(arg2);
}


SWIGEXPORT jlong JNICALL Java_kovanJNI_Servo_1position(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Servo *arg1 = (Servo *) 0 ;
  Servo::ticks_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Servo **)&jarg1; 
  result = (Servo::ticks_t)((Servo const *)arg1)->position();
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_kovanJNI_delete_1Servo(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Servo *arg1 = (Servo *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Servo **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_kovanJNI_AButton_1SWIGUpcast(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong baseptr = 0;
    (void)jenv;
    (void)jcls;
    *(AbstractButton **)&baseptr = *(AButton **)&jarg1;
    return baseptr;
}

SWIGEXPORT jlong JNICALL Java_kovanJNI_BButton_1SWIGUpcast(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong baseptr = 0;
    (void)jenv;
    (void)jcls;
    *(AbstractButton **)&baseptr = *(BButton **)&jarg1;
    return baseptr;
}

SWIGEXPORT jlong JNICALL Java_kovanJNI_ZButton_1SWIGUpcast(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong baseptr = 0;
    (void)jenv;
    (void)jcls;
    *(AbstractButton **)&baseptr = *(ZButton **)&jarg1;
    return baseptr;
}

#ifdef __cplusplus
}
#endif

