/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class kovanJNI {
  public final static native float Battery_powerLevel();
  public final static native long new_Battery();
  public final static native void delete_Battery(long jarg1);
  public final static native void delete_AbstractButton(long jarg1);
  public final static native void AbstractButton_setText(long jarg1, AbstractButton jarg1_, String jarg2);
  public final static native String AbstractButton_text(long jarg1, AbstractButton jarg1_);
  public final static native boolean AbstractButton_isTextDirty(long jarg1, AbstractButton jarg1_);
  public final static native void AbstractButton_setPressed(long jarg1, AbstractButton jarg1_, boolean jarg2);
  public final static native boolean AbstractButton_isPressed(long jarg1, AbstractButton jarg1_);
  public final static native boolean AbstractButton_isNotPressed(long jarg1, AbstractButton jarg1_);
  public final static native void AButton_setText(long jarg1, AButton jarg1_, String jarg2);
  public final static native String AButton_text(long jarg1, AButton jarg1_);
  public final static native boolean AButton_isTextDirty(long jarg1, AButton jarg1_);
  public final static native void AButton_setPressed(long jarg1, AButton jarg1_, boolean jarg2);
  public final static native boolean AButton_isPressed(long jarg1, AButton jarg1_);
  public final static native long new_AButton();
  public final static native void delete_AButton(long jarg1);
  public final static native void BButton_setText(long jarg1, BButton jarg1_, String jarg2);
  public final static native String BButton_text(long jarg1, BButton jarg1_);
  public final static native boolean BButton_isTextDirty(long jarg1, BButton jarg1_);
  public final static native void BButton_setPressed(long jarg1, BButton jarg1_, boolean jarg2);
  public final static native boolean BButton_isPressed(long jarg1, BButton jarg1_);
  public final static native long new_BButton();
  public final static native void delete_BButton(long jarg1);
  public final static native void ZButton_setText(long jarg1, ZButton jarg1_, String jarg2);
  public final static native String ZButton_text(long jarg1, ZButton jarg1_);
  public final static native boolean ZButton_isTextDirty(long jarg1, ZButton jarg1_);
  public final static native void ZButton_setPressed(long jarg1, ZButton jarg1_, boolean jarg2);
  public final static native boolean ZButton_isPressed(long jarg1, ZButton jarg1_);
  public final static native long new_ZButton();
  public final static native void delete_ZButton(long jarg1);
  public final static native long new_Servo(long jarg1);
  public final static native void Servo_setPosition(long jarg1, Servo jarg1_, long jarg2);
  public final static native long Servo_position(long jarg1, Servo jarg1_);
  public final static native void delete_Servo(long jarg1);
  public final static native long AButton_SWIGUpcast(long jarg1);
  public final static native long BButton_SWIGUpcast(long jarg1);
  public final static native long ZButton_SWIGUpcast(long jarg1);
}
