/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ZButton extends AbstractButton {
  private long swigCPtr;

  protected ZButton(long cPtr, boolean cMemoryOwn) {
    super(kovanJNI.ZButton_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ZButton obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        kovanJNI.delete_ZButton(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setText(String text) {
    kovanJNI.ZButton_setText(swigCPtr, this, text);
  }

  public String text() {
    return kovanJNI.ZButton_text(swigCPtr, this);
  }

  public boolean isTextDirty() {
    return kovanJNI.ZButton_isTextDirty(swigCPtr, this);
  }

  public void setPressed(boolean pressed) {
    kovanJNI.ZButton_setPressed(swigCPtr, this, pressed);
  }

  public boolean isPressed() {
    return kovanJNI.ZButton_isPressed(swigCPtr, this);
  }

  public ZButton() {
    this(kovanJNI.new_ZButton(), true);
  }

}
