#ifndef _ARDRONE_CONSTANTS_P_HPP_
#define _ARDRONE_CONSTANTS_P_HPP_

#define ARDRONE_AT_PREFIX "AT*"
#define ARDRONE_AT_SUFFIX "="

#define ARDRONE_AT_REF (ARDRONE_AT_PREFIX "REF" ARDRONE_AT_SUFFIX)
#define ARDRONE_AT_PCMD (ARDRONE_AT_PREFIX "PCMD" ARDRONE_AT_SUFFIX)
#define ARDRONE_AT_FTRIM (ARDRONE_AT_PREFIX "FTRIM" ARDRONE_AT_SUFFIX)
#define ARDRONE_AT_CONFIG (ARDRONE_AT_PREFIX "CONFIG" ARDRONE_AT_SUFFIX)
#define ARDRONE_AT_LED (ARDRONE_AT_PREFIX "LED" ARDRONE_AT_SUFFIX)
#define ARDRONE_AT_ANIM (ARDRONE_AT_PREFIX "ANIM" ARDRONE_AT_SUFFIX)
#define ARDRONE_AT_COMWDG (ARDRONE_AT_PREFIX "COMWDG" ARDRONE_AT_SUFFIX)
#define ARDRONE_AT_CTRL (ARDRONE_AT_PREFIX "CTRL" ARDRONE_AT_SUFFIX)

#define ARDRONE_CMD_SEPARATOR ((char)10)
#define ARDRONE_MAX_CMD_LENGTH (1024)

#define ARDRONE_AT_PORT (5556)
#define ARDRONE_CONFIG_PORT (5559)

#define ARDRONE_NAVDATA_HEADER (0x55667788)

#define ARDRONE_TRUE "TRUE"
#define ARDRONE_FALSE "FALSE"

#define ARDRONE_CFG_GET_CONTROL_MODE (4)
#define ARDRONE_ACK_CONTROL_MODE (5)

#define ARDRONE_NAVDATA_DEMO "general:navdata_demo"
#define ARDRONE_NETWORK_OWNER_MAC "network:owner_mac"

#define ARDRONE_NAVDATA_PORT (5554)

#endif
