;; This file was automatically generated by SWIG (http://www.swig.org).
;; Version 2.0.6
;;
;; Do not make changes to this file unless you know what you are doing--modify
;; the SWIG interface file instead.

(defpackage :kovan
  (:use :common-lisp :ffi))

(in-package :kovan)

(default-foreign-language :stdc)
